/******************************************************************************
*
* Module: Ultrasonic
*
* File Name: ultrasonic.c
*
* Description: Source file for the Ultrasonic driver
*
* Author: Abdallah El-Sakka
*
*******************************************************************************/

#include "../../Utils/std_types.h"
#include "../../MCAL/GPIO/gpio.h"
#include "../../MCAL/ICU/icu.h"
#include <util/delay.h>
#include "ultrasonic.h"

/*******************************************************************************
*                           Global Variables                                  *
*******************************************************************************/

uint8 g_edgeCount = 0;
uint16 g_T_edge 	  = 0;

ICU_ConfigType ICU_conf = {
		F_CPU_8,
		RAISING
};

/*******************************************************************************
*                      Functions Definitions                                  *
*******************************************************************************/


/*
 * Initialize the ICU driver as required.
 * Set up the ICU callback function.
 * Set the direction for the trigger pin as output through
 * the GPIO driver
 */
void Ultrasonic_init(void)
{
	ICU_init(&ICU_conf);
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	GPIO_setupPinDirection(TR_PORT_ID, TR_PIN_ID, PIN_OUTPUT);
}

/*
 * Send the trigger pulse (10us) to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(TR_PORT_ID, TR_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(TR_PORT_ID, TR_PIN_ID, LOGIC_LOW);
}

/*
 * Send the trigger pulse by using the Ultrasonic_Trigger
 * function.
 * Start the measurement process via the ICU driver.
 */
uint16 Ultrasonic_readDistance(void)
{

	Ultrasonic_Trigger();

	uint8 _scale = (110);

	/*
	 *  speed in cm/us
	 */
	uint16 distance = (uint16)((g_T_edge)/(_scale));

	return (distance);
}

/*
 * This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by
 * the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	(++g_edgeCount);

	switch(g_edgeCount)
	{
		case 1:
			ICU_clearTimerValue();
			ICU_setEdgeDetectionType(FALLING);
			break;
		case 2:
			g_T_edge = ICU_getInputCaptureValue();
			ICU_clearTimerValue();
			ICU_setEdgeDetectionType(RAISING);
			g_edgeCount = 0;
			break;
	}
}
